name: transcripcion-audio-app
region: nyc1
services:
  - name: transcripci-n-de-audio
    run_command: python main.py
    environment_slug: "python"
    instance_size_slug: basic-xxs
    instance_count: 1
    image:
      registry_type: "DOCR"
      registry: "transcriptor"
      repository: "transcripcion-audio"
  digest: "sha256:719e47b8a4f6e103c44809f777d7bf9eea8c57868ff5c29c2016fbd316db6116"
    envs:
      - key: WHISPER_MODEL
        value: "small"
      - key: MAX_FILE_SIZE
        value: "209715200"
    http_port: 8888

static_sites: []
