name: Build and push to DigitalOcean Container Registry (DOCR)

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install doctl and authenticate
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login

      - name: Build minimal image (base requirements)
        run: |
          REG=registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}
          REPO=${{ secrets.DOCR_REPOSITORY }}
          SHA_TAG=${{ github.sha }}
          IMAGE_MIN="$REG/$REPO:$SHA_TAG"
          docker build --pull -t "$IMAGE_MIN" --build-arg REQUIREMENTS=config/requirements.txt .
          docker tag "$IMAGE_MIN" "$REG/$REPO:latest"
          docker push "$IMAGE_MIN"
          docker push "$REG/$REPO:latest"

      - name: (Optional) Build full image (heavy deps)
        if: ${{ secrets.DO_FULL_IMAGE == 'true' }}
        run: |
          REG=registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}
          REPO=${{ secrets.DOCR_REPOSITORY }}
          SHA_TAG=${{ github.sha }}
          IMAGE_FULL="$REG/$REPO:${SHA_TAG}-full"
          docker build --pull -t "$IMAGE_FULL" --build-arg REQUIREMENTS=config/requirements-optional.txt .
          docker tag "$IMAGE_FULL" "$REG/$REPO:full-latest"
          docker push "$IMAGE_FULL"
          docker push "$REG/$REPO:full-latest"

      - name: Output image locations
        run: echo "Images pushed to registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}/${{ secrets.DOCR_REPOSITORY }}"

      - name: Update DigitalOcean App (optional)
        if: ${{ secrets.DO_APP_ID != '' }}
        run: |
          # This will use the do_app_spec.yaml; edit it to point to the desired tag (latest or full-latest)
          doctl apps update ${{ secrets.DO_APP_ID }} --spec ./do_app_spec.yaml
